### ISSUE TITLE
Doesn't Parse successfully

### ISSUE THREAD

**Issue by justtn1** [satoqz/rapla-ical-proxy#31]
Hey, I discovered that the tool does not parse successfully for some Rapla links.

E.g. here: 
https://rapla.satoqz.net/rapla/calendar?key=YQ2-UomTsbklupKEMv3vH4m5E_j6QIroyszDQkwLmHk8Y2uLQC59U1TWueddN0FutHxsBf8LrXysBEXpFjjT4AORddKqQTuiMxMWMTLKPZCAxCUR15SUwxJWkNRdROT94o4e7DXCW-WP0tebgwxHyMzAff6TfZWgKbrWWa3-UtPkzkp-AZjv9oratVWtdo4k9ITuYsTQj1nx6FiDZnxQnRq8o78LdZKWneYPdw5HZ9A&salt=-432160255

Not sure if something is different with the link, as the timetable behind the link also doesn't have the controls for the weeks on the top of the page.

**Comment by satoqz** [comment]
Thanks for reporting!

There were two parsing issues that are fixed by https://github.com/satoqz/rapla-ical-proxy/commit/ba4a3a10b532f9961f551ea1d064d39ed3711488 and https://github.com/satoqz/rapla-ical-proxy/pull/32/commits/a918a93ce7868a16054d9b768e5608c5a2b3c7e3 respectively. My comments in the latter commit should be a fun read.
